### ISSUE TITLE
Mobile Blazor Hybrid App

### ISSUE THREAD

**Issue by rajeshsws** [sabitertan/BlazorBarcodeScanner#2]
Hi
I am trying to use your Blazor Barcode Scanner in MobileBlazorBinding Project(hybrid app).
Can't enumerate devices, method not supported.
Error: Can't enumerate devices, method not supported.
    at f.<anonymous> (http://0.0.0.0/_content/ProtrackBarcodeScanner/zxingjs-0.17.1.index.min.js:1:20220)
    at http://0.0.0.0/_content/ProtrackBarcodeScanner/zxingjs-0.17.1.index.min.js:1:18670
    at Object.next (http://0.0.0.0/_content/ProtrackBarcodeScanner/zxingjs-0.17.1.index.min.js:1:18775)
    at http://0.0.0.0/_content/ProtrackBarcodeScanner/zxingjs-0.17.1.index.min.js:1:17688
    at new Promise (<anonymous>)
    at n (http://0.0.0.0/_content/ProtrackBarcodeScanner/zxingjs-0.17.1.index.min.js:1:17467)
    at f._.listVideoInputDevices (http://0.0.0.0/_content/ProtrackBarcodeScanner/zxingjs-0.17.1.index.min.js:1:19984)
    at Object.listVideoInputDevices (http://0.0.0.0/_content/ProtrackBarcodeScanner/BlazorBarcodeScanner.js:4:77)
    at framework://blazor.desktop.js:1:2822
    at new Promise (<anonymous>)

**Comment by sabitertan** [comment]
On a hybrid app I assume you should get camera permission right first. For details https://docs.microsoft.com/en-us/xamarin/essentials/permissions?tabs=android#available-permissions

Also there is more mobile native library to support barcode scanning:
https://github.com/Redth/ZXing.Net.Mobile

**Comment by rajeshsws** [comment]
Hi Sabitertan
I have given the permission but now something different error is coming regrading Inavigator
Zxing.net.Mobile is working fine for xamarin android project by my project is in Blazor MobileBlazorBinding, 
an error is occuring to register Inavigator ineterface on naviigation.pushasync.
I tried to register Inavigator in app.css in android project but problem not solved.
Your BlazorScanner is pretty fast in wasm on web I tested it its wokring fine in chrome. if you can so something MobileBlazorBinding that can solve my bug problem.

**Comment by rajeshsws** [comment]
Problem Solved
Need to pass
 ZXing.Mobile.MobileBarcodeScanner.Initialize(Application);
