### ISSUE TITLE
Error in ListVideoInput Devices

### ISSUE THREAD

**Issue by nssidhu** [sabitertan/BlazorBarcodeScanner#20]
I am getting the following error.
I am using .NET 6 Blazor Wasm Hosted.

Also i never got the prompt that would ask for the permissions on allowing video.

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'BlazorBarcodeScanner.listVideoInputDevices' ('BlazorBarcodeScanner' was undefined).
      Error: Could not find 'BlazorBarcodeScanner.listVideoInputDevices' ('BlazorBarcodeScanner' was undefined).
          at https://localhost:5001/_framework/blazor.webassembly.js:1:328
          at Array.forEach (<anonymous>)
          at a.findFunction (https://localhost:5001/_framework/blazor.webassembly.js:1:296)
          at _ (https://localhost:5001/_framework/blazor.webassembly.js:1:2437)
          at https://localhost:5001/_framework/blazor.webassembly.js:1:3290
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:3271)
          at Object.At [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:58349)
          at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.6.0.0-rc.1.21451.13.js:1:193753)
          at wasm://wasm/00945eda:wasm-function[2590]:0x8073e
Microsoft.JSInterop.JSException: Could not find 'BlazorBarcodeScanner.listVideoInputDevices' ('BlazorBarcodeScanner' was undefined).
Error: Could not find 'BlazorBarcodeScanner.listVideoInputDevices' ('BlazorBarcodeScanner' was undefined).
    at https://localhost:5001/_framework/blazor.webassembly.js:1:328
    at Array.forEach (<anonymous>)
    at a.findFunction (https://localhost:5001/_framework/blazor.webassembly.js:1:296)
    at _ (https://localhost:5001/_framework/blazor.webassembly.js:1:2437)
    at https://localhost:5001/_framework/blazor.webassembly.js:1:3290
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:3271)
    at Object.At [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:58349)
    at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.6.0.0-rc.1.21451.13.js:1:193753)
    at wasm://wasm/00945eda:wasm-function[2590]:0x8073e
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[System.Collections.Generic.List`1[[BlazorBarcodeScanner.ZXing.JS.VideoInputDevice, BlazorBarcodeScanner.ZXing.JS, Version=0.2.4.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at BlazorBarcodeScanner.ZXing.JS.BarcodeReader.GetVideoInputDevicesAsync()
   at BlazorBarcodeScanner.ZXing.JS.BarcodeReader.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by nssidhu** [comment]
Not sure why i was getting this error but cleaning the Application cache from the developer tools fixed everything and it is working now
