### ISSUE TITLE
Could not find 'BlazorBarcodeScanner.listVideoInputDevices' .NET 6 Blazor Wasm Hosted

### ISSUE THREAD

**Issue by ferminv** [sabitertan/BlazorBarcodeScanner#34]
Hello, im getting the following error guys,
I saw the same issue closed but cleaning cache does not work for me because its happening every time i restart the app.
I have everything defined as readme.md file says.
Thanks in advance.

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'BlazorBarcodeScanner.listVideoInputDevices' ('BlazorBarcodeScanner' was undefined).
      Error: Could not find 'BlazorBarcodeScanner.listVideoInputDevices' ('BlazorBarcodeScanner' was undefined).
          at https://localhost:44342/_framework/blazor.webassembly.js:1:328
          at Array.forEach (<anonymous>)
          at a.findFunction (https://localhost:44342/_framework/blazor.webassembly.js:1:296)
          at _ (https://localhost:44342/_framework/blazor.webassembly.js:1:2437)
          at https://localhost:44342/_framework/blazor.webassembly.js:1:3325
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44342/_framework/blazor.webassembly.js:1:3306)
          at Object.St [as invokeJSFromDotNet] (https://localhost:44342/_framework/blazor.webassembly.js:1:59849)
          at _mono_wasm_invoke_js_blazor (https://localhost:44342/_framework/dotnet.6.0.3.jvodq9h7vl.js:1:194973)
          at https://localhost:44342/_framework/dotnet.wasm:wasm-function[219]:0x1a0fa
Microsoft.JSInterop.JSException: Could not find 'BlazorBarcodeScanner.listVideoInputDevices' ('BlazorBarcodeScanner' was undefined).

**Comment by sabitertan** [comment]
@ferminv  Can you provide a sample repo so we can look at it? Sounds like `using` statements are missing in `_Imports.cs`

**Comment by sabitertan** [comment]
Closing, no activity.
