### ISSUE TITLE
Exception when I load the component in Blazor Server

### ISSUE THREAD

**Issue by TheDayIsMyEnemy** [sabitertan/BlazorBarcodeScanner#45]
System.NullReferenceException: Object reference not set to an instance of an object.
         at BlazorBarcodeScanner.ZXing.JS.BarcodeReader.StopDecoding()
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass69_0.<Dispose>g__NotifyExceptions|2(List`1 exceptions)

This is where I load the scripts:

    <script src="_framework/blazor.server.js"></script>
    <script src="_content/BlazorBarcodeScanner.ZXing.JS/zxingjs.index.min.js"></script>
    <script src="_content/BlazorBarcodeScanner.ZXing.JS/BlazorBarcodeScanner.js"></script>
</body>

And this is the component:

```
@page "/demo"
@using BlazorBarcodeScanner.ZXing.JS

<PageTitle>Index</PageTitle>

<div class="d-flex flex-column align-items-center min-vh-100">

    <BarcodeReader @ref="Reader" Title=""
                   StartCameraAutomatically="false"
                   ShowStart="false"
                   ShowReset="false"
                   ShowToggleTorch="false"
                   ShowVideoDeviceList="false"
                   ShowResult="false"
                   VideoWidth="400"
                   VideoHeight="300"
                   OnBarcodeReceived="OnBarcodeReceived" />


    <div style="height: 75px; margin-top: 50px;">
        @if (BarcodeText != null)
        {
            <p>Barcode Result: @BarcodeText</p>
        }
    </div>

    <div>
        <button type="button" class="btn btn-primary btn-lg mx-lg-1"
                @onclick="Stop">
            Stop
        </button>
        <button type="button" class="btn btn-primary btn-lg mx-lg-1"
                @onclick="Start">
            Start
        </button>

    </div>
</div>
```

**Comment by sallen23322** [comment]
my controller is listed as follows

   <BlazorBarcodeScanner.ZXing.JS.BarcodeReader 
Title="Scan Barcode from Camera"
                                                 @ref="reader"
                                                 OnBarcodeReceived="OnInitFrame"
                                                 StartCameraAutomatically="false"
                                                 ShowStart="true"
                                                 DecodedPictureCapture="true"
                                                 ShowResult="false"
                                                 ShowReset="true"
                                                 ShowToggleTorch="false"
                                                 ShowVideoDeviceList="true"
                                                 VideoWidth="300"
                                                 VideoHeight="200" />

**Comment by sallen23322** [comment]
my page layout:
```
@page "/BarcodeReader"
<h3>BarcodeReader</h3>

@using BlazorBarcodeScanner.ZXing.JS

@using Microsoft.Extensions.Logging
@inject ILogger<Error> Logger
@inject NavigationManager NavManager
@inject IJSRuntime jsRuntime
@inject HttpClient Http



    <BlazorBarcodeScanner.ZXing.JS.BarcodeReader Title="Scan Barcode from Camera"
                                                 @ref="reader"
                                                 OnBarcodeReceived="OnInitFrame"
                                                 StartCameraAutomatically="false"
                                                 ShowStart="true"
                                                 DecodedPictureCapture="true"
                                                 ShowResult="false"
                                                 ShowReset="true"
                                                 ShowToggleTorch="false"
                                                 ShowVideoDeviceList="true"
                                                 VideoWidth="300"
                                                 VideoHeight="200" />

 
    <h1>Passed In Value @scanned</h1>
    <CascadingValue Value="this">
        @ChildContent
    </CascadingValue>

    <ErrorBoundary>
        @error
        @errorBoundary
    </ErrorBoundary>

    @code{
    [CascadingParameter]
    public Error? Error { get; set; }
    public string error { get; set; }
    private string LocalBarcodeText;
    public string scanned { get; set; }

    private void LocalReceivedBarcodeText(BarcodeReceivedEventArgs args)
    {
        this.LocalBarcodeText = args.BarcodeText;

        StateHasChanged();
    }
    BlazorBarcodeScanner.ZXing.JS.BarcodeReader reader;

    private string _img = string.Empty;

    private async Task OnGrabFrame(MouseEventArgs args)
    {
        _img = await reader.Capture();
        scanned = reader.BarcodeText;
        StateHasChanged();
    }
    private async Task OnInitFrame(EventArgs args)
    {
               scanned = reader.BarcodeText;
        StateHasChanged();
    }
    protected override void OnInitialized()
    {
        try
        {
            jsRuntime.InvokeVoidAsync("BlazorBarcodeScanner", scanned);

        }
        catch (Exception ex)
        {
            Error?.ProcessError(ex);
            error = ex.Message;
            throw new Exception(error);
        }
        finally { }
        StateHasChanged();

    }
    ErrorBoundary errorBoundary;

    protected override void OnParametersSet()
    {
        errorBoundary?.Recover();
    }

    [Parameter]
    public RenderFragment? ChildContent { get; set; }

    public void ProcessError(Exception ex)
    {
        Logger.LogError("Error:ProcessError - Type: {Type} Message: {Message}",
            ex.GetType(), ex.Message);
    }



    }

```

**Comment by TheDayIsMyEnemy** [comment]
@sallen23322  is this a working solution?
