### ISSUE TITLE
JSDisconnectedException in published project

### ISSUE THREAD

**Issue by Syntaxrabbit** [sabitertan/BlazorBarcodeScanner#46]
Good afternoon!

Today I made some first experiments with this awesome project (nuget package). Thanks a lot for that.

Unfortunately, I cannot use it at all in "published" server-side projects.
(Debugging mode works without any issues.)

As soon, as I request a page containing the control, the following exception is thrown:

```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '4u9IgHDmxj1lynbcrvGjWBZE0endyewjrgqRO-pfngQ'.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at BlazorBarcodeScanner.ZXing.JS.BarcodeReaderInterop.StopDecoding()
         at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)
```

I can "delay" the exception by making the control rendering conditional after pressing some button, but as soon as it is rendered, the application crashes and I cannot interact anymore.
Googling around did not provide any useful information so far, but what made me suspicious is the fact that the stack trace mentions "StopDecoding" although this happens directly after opening the page.

Feel free to ask for further details if needed.

Best regards!

**Comment by sabitertan** [comment]
Can you give a sample repo to show how you set it up, so we can try to reproduce it.

**Comment by Syntaxrabbit** [comment]
I will provide a sample project this evening. Thank you for your quick reply.Message ID: ***@***.***>

**Comment by Syntaxrabbit** [comment]
I fixed it for you: https://github.com/sabitertan/BlazorBarcodeScanner/pull/47

Have a nice evening! :-)
