### ISSUE TITLE
Blazor server app in .net 8 

### ISSUE THREAD

**Issue by rajeshsws** [sabitertan/BlazorBarcodeScanner#65]
Local server its working but after deployment on server below error us facing
Can't enumerate devices, method not supported. Error: Can't enumerate devices, method not supported. at t.BrowserMultiFormatReader.<anonymous> (http://192.168.90.220:499/_content/BlazorBarcodeScanner.ZXing.JS/zxingjs.index.min.js:15:28105) at Generator.next (<anonymous>) at http://192.168.90.220:499/_content/BlazorBarcodeScanner.ZXing.JS/zxingjs.index.min.js:15:27264 at new Promise (<anonymous>) at P (http://192.168.90.220:499/_content/BlazorBarcodeScanner.ZXing.JS/zxingjs.index.min.js:15:27009) at t.BrowserMultiFormatReader.listVideoInputDevices (http://192.168.90.220:499/_content/BlazorBarcodeScanner.ZXing.JS/zxingjs.index.min.js:15:27944) at Object.listVideoInputDevices (http://192.168.90.220:499/_content/BlazorBarcodeScanner.ZXing.JS/BlazorBarcodeScanner.js:92:77) at http://192.168.90.220:499/_framework/blazor.server.js:1:3244 at new Promise (<anonymous>) at y.beginInvokeJSFromDotNet (http://192.168.90.220:499/_framework/blazor.server.js:1:3201)

**Comment by 99cm234** [comment]
getusermedia requires secure connection. Use https and the error will go away. 
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
